services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./storage:/app/storage
      # ビルド済みのフロントエンドをマウントする
      - ./frontend/dist:/app/frontend/dist
    env_file:
      - .env
    restart: unless-stopped
