services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./storage:/app/storage
      # ビルド済みのフロントエンドをマウントする
      - ./frontend/dist:/app/frontend/dist
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.tauri-dev
    volumes:
      - ./frontend:/app/frontend # ホストのfrontendディレクトリをコンテナにマウント
      - /tmp/.X11-unix:/tmp/.X11-unix # X11ソケットをマウント
    environment:
      - DISPLAY=${DISPLAY} # ホストのDISPLAY環境変数をコンテナに渡す
      - VITE_API_BASE_URL=http://backend:3000
    working_dir: /app/frontend # frontendディレクトリをワーキングディレクトリにする
    ports:
      - "5173:5173" # Viteの開発サーバーポート
    user: devuser # Dockerfileで作成したユーザー